### ISSUE TITLE
Apple Dialog Doesnot close

### ISSUE THREAD

**Issue by pg598595** [johncodeos-blog/SignInWithAppleAndroidExample#1]
I have implemented the whole process, 
It works perfectly fine for apple login,
But it is not closing dialog after successful login with apple credentials.

Can you please help.

**Comment by johncodeos** [comment]
Are you sure the request is successful?
Only if the request returns 'success=' will close the dialog. 

Add `Log.d("TAG", request.url.toString())` in the `shouldOverrideUrlLoading(view: WebView?,request: WebResourceRequest?): Boolean` to see what your backend server returns.

**Comment by pg598595** [comment]
This log is not printed. Instead, it directly takes to the redirect URL given in constants.
![Screenshot_1588912845](https://user-images.githubusercontent.com/25722093/81371444-79adde80-9115-11ea-8485-e306a727c792.png)

**Comment by johncodeos** [comment]
Did you set up the [backend server](https://github.com/johncodeos-blog/SignInWithAppleBackendServer) correctly?

**Comment by pg598595** [comment]
yes, setup is done correctly, now it shows on result like this.
![Screenshot_1589210596](https://user-images.githubusercontent.com/25722093/81580056-8e66cc80-93ca-11ea-9dde-a49c95ef051f.png)

**Comment by johncodeos** [comment]
Do you use a domain with https as a callback URL? 
Did you set up this callback URL on Apple's dashboard?

**Comment by pg598595** [comment]
yes

**Comment by johncodeos** [comment]
Try the demo app with your keys (CLIENT_ID, REDIRECT_URI) and see if you get the same results.

If you got the same thing, follow again the step **Step 1: Set up your app in the Apple Developer Account**

**Comment by pg598595** [comment]
Ok Thank you, I will try again

**Comment by pg598595** [comment]
Solved the issue By converting Redirect URL and getting  it from overriding shouldOverrideUrlLoading method request
